import { Injectable } from '@nestjs/common';
import { PassportStrategy } from '@nestjs/passport';
import { Strategy, VerifyCallback } from 'passport-google-oauth20';
import { ConfigService } from '@nestjs/config';

@Injectable()
export class GoogleStrategy extends PassportStrategy(Strategy, 'google') {
  constructor(config: ConfigService) {
    const baseUrl = config.get<string>('API_BASE_URL', 'http://localhost:4000');
    super({
      clientID: config.getOrThrow<string>('GOOGLE_CLIENT_ID'),
      clientSecret: config.getOrThrow<string>('GOOGLE_CLIENT_SECRET'),
      callbackURL: `${baseUrl}/api/v1/auth/google/callback`,
      scope: ['profile', 'email'],
      // CSRF: state parameter is auto-generated by Passport.
      // For production, configure a Redis-backed state store via `store` option.
    });
  }

  async validate(_accessToken: string, _refreshToken: string, profile: any, done: VerifyCallback) {
    return done(null, profile);
  }
}
